#!/bin/bash
# joe brendler - 29 May 2024
# gp - git-push customized for automating push to my JosephBrendler repositories
#
source /usr/local/sbin/script_header_brendlefly

BUILD=0
VERBOSE=$TRUE
verbosity=6

gituser="JosephBrendler"
gitpass="ca8850b956b3ffcfdab1fc09f3d893402c2aad13"
gitrepo=""

#-----[ functions ]----------------------------------------------------------------------------
usage() {
  E_message "Usage: gp <repo>"
  echo "  where the first character of <repo> identifies the repository --"
  echo "  [jJ] = joetoo"
  echo "  [mM] = myUtilities"
  echo "  [iI] = IoT_C2"
  echo "  [bB] = joeBot"
  echo "  [sS] = MultiSensor"
  echo "  [pP] = Stepper"
}

gitpush() {
  case $1 in
    [jJ] ) gitrepo="joetoo" ;;
    [mM] ) gitrepo="myUtilities";;
    [iI] ) gitrepo="IoT_C2" ;;
    [bB] ) gitrepo="joeBot" ;;
    [sS] ) gitrepo="MultiSensor" ;;
    [pP] ) gitrepo="Stepper" ;;
    *    ) E_message "Error: Invalid repository identified [ $1 ]"; usage;;
  esac
  eval "git push https://${gituser}:${gitpass}@github.com/${gituser}/${gitrepo}.git master"
}

#-----[ main script ]---------------------------------------------------------------------------
checknotroot

[ $# -ne 1 ] && usage

gitpush "${1:0:1}"


