#!/bin/bash
TRUE=0
vcgencmdfile=/usr/bin/vcgencmd
VPN_LED=2          # raspi gpio pin 3 (Services LED)(yellow)
blinkwait=0.05     # s wait during fluttler blink
blinklongwait=0.5  # s wait during blink between flutters
wait_time=2        # s wait for ping
vpn_server_ip="192.168.63.1"
result=100         # % packet loss (want 0)

#-----[ functions ]---------------------------
initialize_pig() {
  pigs m ${1} w         # set mode output
}

light_off() {
  pigs w ${1} 0
}

light_on() {
  pigs w ${1} 1
}

blink_light() {
  # blink and then light my LED (on pin designated by arg 1 $1 )
  LED=$1
  for ((i=0;i<5;i++))       # blink on-off 5 times, quickly
  do
    light_on ${LED}
    sleep ${blinkwait}
    light_off ${LED}
    sleep ${blinkwait}
  done
}

check_vpn() {
  result=$(ping -c1 -w${wait_time} ${vpn_server_ip} | grep transmitted | \
           cut -d',' -f3 | cut -d'%' -f1 | sed 's/ //g')
}

#-----[ main script ]-----------------------------------

killall pi4_vpn_watch_for_led   # kill any residual vpn-watch (if run interactively)

initialize_pig ${VPN_LED}

while [[ $TRUE ]]
do
  check_vpn
  if [[ ${result} == 0 ]]   # no loss; good vpn
  then
    blink_light ${VPN_LED}
    light_on ${VPN_LED}
  else
    blink_light ${VPN_LED}
    light_off ${VPN_LED}
    /usr/local/sbin/stopvpn
    /usr/local/sbin/startvpn r
  fi
  sleep 30
done
