#!/bin/bash
TRUE=0
vcgencmdfile=/usr/bin/vcgencmd
SVCs_LED=3         # raspi gpio pin 3 (Services LED)(yellow)
blinkwait=0.05     # s wait during fluttler blink
blinklongwait=0.5  # s wait during blink between flutters
pi4_svc_watch_program=/usr/local/sbin/pi4_svc_watch_for_led

#-----[ functions ]---------------------------
initialize_pig() {
  pigs m ${1} w         # set mode output
}

light_off() {
  pigs w ${1} 0
}

light_on() {
  pigs w ${1} 1
}

blink_light() {
  # blink and then light my LED (on pin designated by arg 1 $1 )
  LED=$1
  for ((i=0;i<5;i++))       # blink on-off 5 times, quickly
  do
    light_on ${LED}
    sleep ${blinkwait}
    light_off ${LED}
    sleep ${blinkwait}
  done
}

listmatchedprocs() {
  ps -aef | grep ${1} | grep -v grep | sed 's/  */ /g' | \
                   cut -d' ' -f2 | sort
}

killotherslikeme() {
  # kill other instances of this program
  keeper=$$   # get my own process number
  for x in $(listmatchedprocs ${pi4_svc_watch_program} | grep -v ${keeper})
  do
    kill -9 ${x}
  done
}

#-----[ main script ]-----------------------

killotherslikeme

initialize_pig ${SVCs_LED}

while [[ $TRUE ]]
do
  if [[ ! $(rc-status | grep '\[' | grep -v started) ]]   ## all services are "started"
  then
    blink_light ${SVCs_LED}
    light_on ${SVCs_LED}
  else
    blink_light ${SVCs_LED}
    light_off ${SVCs_LED}
  fi
  sleep 30
done
