#!/bin/bash
TRUE=0
cputempfile=/sys/class/thermal/thermal_zone0/temp
vcgencmdfile=/usr/bin/vcgencmd
temp_threshold=60  # deg celcius above which to consider cpu to be hot
TEMP_LED=4            # raspi gpio pin 4 (Temp LED)(red)
SVC_LED=3             # raspi gpio pin 3 (Servoces LED)(yellow)
NET_LED=2             # raspi gpio pin 2 (Network LED)(green)
GPIO_CHIP=4           # gpiochip number for libgpiod (gpioset)
blinkwait=0.05     # s wait during fluttler blink
blinklongwait=0.5  # s wait during blink between flutters

[[ $# -eq 0 ]] && echo "Missing argument. Please supply threshold temp." && exit
if [[ $1 -gt 0 ]] && [[ $1 -le 99 ]]
then
  temp_threshold=$1  # reassign. deg celcius above which to consider cpu to be hot
  echo "temp_threshold: ${temp_threshold}"
else
  echo "Bad argument. Please supply valid threshold temp. (0-99 C)"
  exit
fi

#-----[ functions ]---------------------------
light_off() {
  gpioset -c${GPIO_CHIP} -t0 ${1}=0
}

light_on() {
  gpioset -c${GPIO_CHIP} -t0 ${1}=1
}

blink_light() {
  # blink and then light my LED (on pin designated by arg 1 $1 )
  LED=$1
  for ((i=0;i<5;i++))       # blink on-off 5 times, quickly
  do
    light_on ${LED}
    sleep ${blinkwait}
    light_off ${LED}
    sleep ${blinkwait}
  done
}

#-----[ main script ]-----------------------

light_off ${TEMP_LED}
sleep ${blinkwait}
blink_light ${TEMP_LED}

while [[ $TRUE ]]
do
  cpu_temp=$(cat ${cputempfile} 2>/dev/null)
  int_temp=${cpu_temp:0:2}
#  echo "cpu_temp: ${cpu_temp:0:2}.${cpu_temp:2:2}   int_temp: ${int_temp}"
  [[ ${int_temp} -ge ${temp_threshold} ]] && light_on ${TEMP_LED} || light_off ${TEMP_LED}
  sleep 30
done
