#!/bin/bash
TRUE=0
vcgencmdfile=/usr/bin/vcgencmd
TEMP_LED=4            # raspi gpio pin 4 (Temp LED)(red)
SVC_LED=3             # raspi gpio pin 3 (Servoces LED)(yellow)
NET_LED=2             # raspi gpio pin 2 (Network LED)(green)
GPIO_CHIP=4           # gpiochip number for libgpiod (gpioset)
blinkwait=0.05     # s wait during fluttler blink
blinklongwait=0.5  # s wait during blink between flutters

#-----[ functions ]---------------------------

light_off() {
  gpioset -c${GPIO_CHIP} -t0 ${1}=0
}

light_on() {
  gpioset -c${GPIO_CHIP} -t0 ${1}=1
}

blink_light() {
  # blink and then light my LED (on pin designated by arg 1 $1 )
  LED=$1
  for ((i=0;i<5;i++))       # blink on-off 5 times, quickly
  do
    light_on ${LED}
    sleep ${blinkwait}
    light_off ${LED}
    sleep ${blinkwait}
  done
}

#-----[ main script ]-----------------------

light_off ${SVC_LED}

while [[ $TRUE ]]
do
  if [[ ! $(rc-status | grep '\[' | grep -v started) ]]   ## all services are "started"
  then
    blink_light ${SVC_LED}
    light_on ${SVC_LED}
  else
    blink_light ${SVC_LED}
    light_off ${SVC_LED}
  fi
  sleep 30
done
