#!/bin/bash
TRUE=0
vcgencmdfile=/usr/bin/vcgencmd
TEMP_LED=4            # raspi gpio pin 4 (Temp LED)(red)
SVC_LED=3             # raspi gpio pin 3 (Servoces LED)(yellow)
NET_LED=2             # raspi gpio pin 2 (Network LED)(green)
GPIO_CHIP=4           # gpiochip number for libgpiod (gpioset)
blinkwait=0.05     # s wait during fluttler blink
blinklongwait=0.5  # s wait during blink between flutters
wait_time=2        # s wait for ping
vpn_server_ip="192.168.67.1"
result=100         # % packet loss (want 0)

#-----[ functions ]---------------------------

light_off() {
  gpioset -c${GPIO_CHIP} -t0 ${1}=0
}

light_on() {
  gpioset -c${GPIO_CHIP} -t0 ${1}=1
}

blink_light() {
  # blink and then light my LED (on pin designated by arg 1 $1 )
  LED=$1
  for ((i=0;i<5;i++))       # blink on-off 5 times, quickly
  do
    light_on ${LED}
    sleep ${blinkwait}
    light_off ${LED}
    sleep ${blinkwait}
  done
}

check_vpn() {
  result=$(ping -c1 -w${wait_time} ${vpn_server_ip} | grep transmitted | \
           cut -d',' -f3 | cut -d'%' -f1 | sed 's/ //g')
}

#-----[ main script ]-----------------------

light_off ${VPN_LED}

while [[ $TRUE ]]
do
  check_vpn
  if [[ ${result} == 0 ]]   # no loss; good vpn
  then
    blink_light ${VPN_LED}
    light_on ${VPN_LED}
  else
    blink_light ${VPN_LED}
    light_off ${VPN_LED}
    /usr/local/sbin/stopvpn
    /usr/local/sbin/startvpn r
  fi
  sleep 30
done
