#!/bin/bash
source /usr/local/sbin/script_header_brendlefly
BUILD=0.0

#-----[ functions ]----------------------
usage() {
  E_message "Error; bad argument(s)"
  message "  ${BYon}Usage: ${BGon}inker_mon [q]${Boff}"
  message "  ${LBon}q = quiet (no separator; e.g. ${BGon}watch tinker_mon q${Boff}"
  exit 1
}

#-----[ main script ]--------------------
[[ $# -gt 1 ]] && usage

# measure temperature in millicelcius; convert to degrees celcius and farenheit
rawC="$(cat /sys/class/thermal/thermal_zone0/temp)"
tempC=$(bc <<<"scale=1; ${rawC}/1000")
tempF=$(bc <<<"scale=1; (($tempC / 5.0) * 9.0) + 32.0")

echo "Temp: $tempC C"
echo "Temp: $tempF F"
echo

# measure frequency in herz, three ways; convert to Mhz
scaling_gov=$(cat /sys/devices/system/cpu/cpufreq/policy0/scaling_governor)
raw_sfreq=$(cat /sys/devices/system/cpu/cpu0/cpufreq/scaling_cur_freq)
raw_minfreq=$(cat /sys/devices/system/cpu/cpu0/cpufreq/cpuinfo_min_freq)
raw_maxfreq=$(cat /sys/devices/system/cpu/cpu0/cpufreq/cpuinfo_max_freq)
sfreq=$(bc <<<"scale=2; ${raw_sfreq}/1000000")
minfreq=$(bc <<<"scale=2; ${raw_minfreq}/1000000")
maxfreq=$(bc <<<"scale=2; ${raw_maxfreq}/1000000")

echo "Min/Max CPU freqs: ${minfreq} Mhz - ${maxfreq} Mhz"
echo "Current scaling governor: $scaling_gov"
echo "Current scaling freq: $sfreq Mhz"
