#!/bin/bash
arg=""; ip_address=""; class_c=""; resolveconf_file=""; twait=""  #initialize null

twait=5
blinkwait=0.05
blinklongwait=0.5
#twait=180
ip_address=$(ifconfig wlan0 | grep inet | sed 's/^[[:space:]]*//' | cut -d' ' -f2)
class_c=$(echo $ip_address | cut -d'.' -f1,2,3)

#-----[ functions ]-----------------------------------
blink_off() {
  # blink and then light my LED on GPIO pin 36 (ASUS pin gpio223)
  echo 223 > /sys/class/gpio/export             # initialize
  echo out > /sys/class/gpio/gpio223/direction
  echo 0 > /sys/class/gpio/gpio223/value        # start with LED off
  echo 223 > /sys/class/gpio/unexport           # "disconnect"
}


blink_light() {
  # blink and then light my LED on GPIO pin 36 (ASUS pin gpio223)
  echo 223 > /sys/class/gpio/export             # initialize
  echo out > /sys/class/gpio/gpio223/direction
  echo 0 > /sys/class/gpio/gpio223/value        # start with LED off
  for ((i=0;i<5;i++))                           # blink on-off 5 times, quickly
  do
    echo 1 > /sys/class/gpio/gpio223/value
    sleep ${blinkwait}
    echo 0 > /sys/class/gpio/gpio223/value
    sleep ${blinkwait}
  done
  sleep ${blinklongwait}                        # pause
  echo 1 > /sys/class/gpio/gpio223/value        # now keep LED on
  echo 223 > /sys/class/gpio/unexport           # "disconnect"
}

#-----[ main ]-----------------------------------
blink_off
case ${class_c} in
  "192.168.62"|"192.168.3"|"192.168.7") arg="l";;
  *) arg="r";;
esac

case ${arg} in
  "l") resolveconf_file="/root/bin/resolv.conf.local";;
  "r") resolveconf_file="/root/bin/resolv.conf.remote";;
  *)   resolveconf_file="/root/bin/resolv.conf.good";;
esac

echo "will copy [ ${resolveconf_file} ] to /etc/resolv.conf"

## preserve the right resolv.conf, check service status
##  [[ true only if all services are "started" ]], and
##  if success, then blink/light LED
(sleep ${twait} && [[ ! $(rc-status | grep '\[' | grep -v started) ]] && \
  chattr -i /etc/resolv.conf && \
  cp ${resolveconf_file} /etc/resolv.conf && \
  chattr +i /etc/resolv.conf ) && \
blink_light &
