#!/bin/bash
arg=""; ip_address=""; class_c=""; resolveconf_file=""; twait=""  #initialize null

#ENABLE="true"
#RASPBERRY="true"
ENABLE="false"
RASPBERRY="false"

twait=10
blinkwait=0.05
blinklongwait=0.5
#twait=180
ip_address=$(ifconfig wlan0 | grep inet | sed 's/^[[:space:]]*//' | cut -d' ' -f2)
class_c=$(echo $ip_address | cut -d'.' -f1,2,3)

#-----[ functions ]-----------------------------------
blink_light() {
  # blink and then light my LED on GPIO pin 36 (ASUS pin gpio223)
  echo 223 > /sys/class/gpio/export             # initialize
  echo out > /sys/class/gpio/gpio223/direction
  echo 0 > /sys/class/gpio/gpio223/value        # start with LED off
  for ((i=0;i<5;i++))                           # blink on-off 5 times, quickly
  do
    echo 1 > /sys/class/gpio/gpio223/value
    sleep ${blinkwait}
    echo 0 > /sys/class/gpio/gpio223/value
    sleep ${blinkwait}
  done
  sleep ${blinklongwait}                        # pause
  echo 1 > /sys/class/gpio/gpio223/value        # now keep LED on
  echo 223 > /sys/class/gpio/unexport           # "disconnect"
}

#-----[ main ]-----------------------------------
[[ "${ENABLE}" == "false" ]] && exit

case ${class_c} in
  "192.168.62"|"192.168.3"|"192.168.7") arg="l";;
  *) arg="r";;
esac

case ${arg} in
  "l") resolveconf_file="/root/bin/resolv.conf.local";;
  "r") resolveconf_file="/root/bin/resolv.conf.remote";;
  *)   resolveconf_file="/root/bin/resolv.conf.good";;
esac

echo "will copy [ ${resolveconf_file} ] to /etc/resolv.conf after starting vpn..."
echo "will delay and then run \"startvpn ${arg}\""

# start the vpn, preserve the right resolv.conf, and if success, then blink/light LED
(sleep ${twait} && /usr/local/sbin/startvpn ${arg} && \
  chattr -i /etc/resolv.conf && \
  cp ${resolveconf_file} /etc/resolv.conf && \
  chattr +i /etc/resolv.conf ) && \
[[ "${RASPBERRY}" == "true" ]] && blink_light &
