#!/bin/bash
#  backport from Pi5 for tinkerboar
#   (changes only GPIO_CHIP/PIN and watch progs)
#!/bin/bash
TRUE=0
FALSE=
vcgencmdfile=/usr/bin/vcgencmd
#TEMP_LED=4            # raspi gpio pin 4 (Temp LED)(red)
#SVC_LED=3             # raspi gpio pin 3 (Servoces LED)(yellow)
#NET_LED=2             # raspi gpio pin 2 (Network LED)(green)
TEMP_LED=18            # GP7C2: chip 7, (C=2*8)+2=Line 18 (pin 28) (this is the only change #1)
SVC_LED=8              # GP7B0: chip 7, (B=1*8)+0=Line 8 (pin 37) (this is the only change #1)
NET_LED=7              # GP7A7: chip 7, (A=0*8)+7=Line 7 (pin 36) (this is the only change #1)
#GPIO_CHIP=4           # gpiochip number for libgpiod (gpioset)
GPIO_CHIP=7           # backport from Pi5 (this is the only change #1)
blinkwait=0.05        # s wait during fluttler blink
blinklongwait=0.5     # s wait during blink between flutters
#VERBOSE=$FALSE
VERBOSE=$TRUE    # verbpse logging pm/off
verbosity=2     # 0: none; 1: restarts; 2: errors; 3: success; 4: dump vectors on restart

#PROG_NAME=pi5_svc_watch_for_led
PROG_NAME=usr/local/sbin/tinker_svc_watch_for_led (this is the only change #2)

#-----[ functions ]---------------------------

light_off() {
  gpioset -c${GPIO_CHIP} -t0 ${1}=0
}

light_on() {
  gpioset -c${GPIO_CHIP} -t0 ${1}=1
}

blink_light() {
  # blink and then light my LED (on pin designated by arg 1 $1 )
  for ((i=0;i<10;i++))       # blink on-off 5 times, quickly
  do
    gpioset -c${GPIO_CHIP} -t0 ${1}=$(( $i % 2 ))
    sleep ${blinkwait}
  done
}

#-----[ main script ]-----------------------

light_off ${SVC_LED}

while [[ $TRUE ]]
do
  result=$(rc-status | grep '\[' | grep -v started)
  if [[ ! ${result} ]]   ## all services are "started"
  then
    [[ $VERBOSE ]] && [[ verbosity -ge 3 ]] && \
      /usr/bin/logger -p cron.notice "${PROG_NAME} success -- Result: all services are started"
    blink_light ${SVC_LED}
    light_on ${SVC_LED}
  else
    [[ $VERBOSE ]] && [[ verbosity -ge 2 ]] && \
      /usr/bin/logger -p cron.notice "${PROG_NAME} failure -- Result: ${result}"
    blink_light ${SVC_LED}
    light_off ${SVC_LED}
  fi
  sleep 30
done
