#!/bin/bash
#  backport from Pi5 for tinkerboar
#   (changes only GPIO_CHIP/PIN and watch progs)
TRUE=0
FALSE=
cputempfile=/sys/class/thermal/thermal_zone0/temp
vcgencmdfile=/usr/bin/vcgencmd
temp_threshold=60  # deg celcius above which to consider cpu to be hot
#TEMP_LED=4            # raspi gpio pin 4 (Temp LED)(red)
#SVC_LED=3             # raspi gpio pin 3 (Servoces LED)(yellow)
#NET_LED=2             # raspi gpio pin 2 (Network LED)(green)
TEMP_LED=18            # GP7C2: chip 7, (C=2*8)+2=Line 18 (pin 28) (this is the only change #1)
SVC_LED=8              # GP7B0: chip 7, (B=1*8)+0=Line 8 (pin 37) (this is the only change #1)
NET_LED=7              # GP7A7: chip 7, (A=0*8)+7=Line 7 (pin 36) (this is the only change #1)
#GPIO_CHIP=4           # gpiochip number for libgpiod (gpioset)
GPIO_CHIP=7           # backport from Pi5 (this is the only change #1)
blinkwait=0.05     # s wait during fluttler blink
blinklongwait=0.5  # s wait during blink between flutters
#VERBOSE=$FALSE
VERBOSE=$TRUE    # verbpse logging pm/off
verbosity=2     # 0: none; 1: restarts; 2: errors; 3: success; 4: dump vectors on restart

#PROG_NAME="pi5_temp_watch_for_led"
PROG_NAME=/usr/local/sbin/tinker_temp_watch_for_led

[[ $# -eq 0 ]] && echo "Missing argument. Please supply threshold temp." && exit
if [[ $1 -gt 0 ]] && [[ $1 -le 99 ]]
then
  temp_threshold=$1  # reassign. deg celcius above which to consider cpu to be hot
  echo "temp_threshold: ${temp_threshold}"
else
  echo "Bad argument. Please supply valid threshold temp. (0-99 C)"
  exit
fi

#-----[ functions ]---------------------------
light_off() {
  gpioset -c${GPIO_CHIP} -t0 ${1}=0
}

light_on() {
  gpioset -c${GPIO_CHIP} -t0 ${1}=1
}

blink_light() {
  # blink and then light my LED (on pin designated by arg 1 $1 )
  for ((i=0;i<10;i++))       # blink on-off 5 times, quickly
  do
    gpioset -c${GPIO_CHIP} -t0 ${1}=$(( $i % 2 ))
    sleep ${blinkwait}
  done
}

#-----[ main script ]-----------------------

light_off ${TEMP_LED}
sleep ${blinkwait}
blink_light ${TEMP_LED}

while [[ $TRUE ]]
do
  cpu_temp=$(cat ${cputempfile} 2>/dev/null)
  int_temp=${cpu_temp:0:2}
  if [[ ${int_temp} -ge ${temp_threshold} ]]
  then
    [[ $VERBOSE ]] && [[ verbosity -ge 2 ]] && \
      /usr/bin/logger -p cron.notice "${PROG_NAME} failure -- CPU Temp: ${int_temp} C [ > threshold: ${temp_threshold} C ]"
    light_on ${TEMP_LED}
  else
    [[ $VERBOSE ]] && [[ verbosity -ge 3 ]] && \
      /usr/bin/logger -p cron.notice "${PROG_NAME} success -- CPU Temp: ${int_temp} C [ < threshold: ${temp_threshold} C ]"
    light_off ${TEMP_LED}
  fi
  sleep 30
done
