#!/bin/bash
# kernelupdate-tinker -- Joe Brendler 11 August 2023
# adapted from kernelupdate-dom0 of October 2021,
#   makeU-distrib-tar of February 2022, and
#   installU_onServer of February 2022
#
# Interactively issue the sequence of commands that accomplishes a kernel update for a tinkerboard
#
# this process assumes you have already cloned the kernel sources and built a kernel at least once --
# build cross compiler
# crossdev --clean --target armv7a-unknown-linux-gnueabihf
# crossdev --b ~2.40 --g ~12.3 --k ~2.37 --l ~6.1 --target armv7a-unknown-linux-gnueabihf
#-----[ retrieve kernel sources ]---------------------------------------
# git clone https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git
# cd linux
# git branch --list --remotes
# git branch --show-current
# git checkout linux-6.4.y
#-----[ Fetch Tinkerboard default kernel config ]------------------------
# curl -L https://raw.githubusercontent.com/TinkerBoard/debian_kernel/develop/arch/arm/configs/min>
#-----[ configure kernel ]-----------------------------------------------
# make ARCH=arm miniarm-rk3288_defconfig -j16
# make ARCH=arm menuconfig -j16
# cp .config /home/joe/MyTinkerboardFiles/.config-6.4.y-baseline
#
# see also instructions at "tinker04-NEW-kernel-custom-rebuild-commands"
#

source /usr/local/sbin/script_header_brendlefly

#---[ local variables ]-------------------------------------------------------
BUILD="0.1.0-20230904"

eval $( grep ^PORTDIR /etc/portage/make.conf )
eval $( grep ^PKGDIR /etc/portage/make.conf )
eval $( grep ^DISTDIR /etc/portage/make.conf )

# custom configuration (to do - override from /etc/kernelupdate-tinker.conf)
VERBOSE=$TRUE
verbosity=3

arch="arm"
cross_compile="armv7a-unknown-linux-gnueabihf-"
model="rk3288-tinker-s"
build_root="/home/joe/MyTinkerboardFiles"
my_devel_dir="/home/joe/myUtilities"
my_ebuild_dir="/home/joe/joetoo/sys-kernel"

# source kernelupdate-tinker.conf in order to load customized settings
#   check each setting below to assign, if needed
#   Note: kernelupdate-tinker.conf in /etc/kernelupdate-tinker/ will override one in pwd
[[ -e kernelupdate-tinker.conf ]] && \
    source kernelupdate-tinker.conf && \
    CONF_DIR=$PWD"/kernelupdate-tinker.conf"
[[ -e /etc/kernelupdate-tinker/kernelupdate-tinker.conf ]] && \
    source /etc/kernelupdate-tinker/kernelupdate-tinker.conf && \
    CONF_DIR="/etc/kernelupdate-tinker/kernelupdate-tinker.conf"

# you should not need to edit anything below this point
sources_dir="${build_root}/linux"
config_dir="${build_root}/kernelconfigs"
build_dir="${build_root}/build"
status_file="${build_dir}/status"
model_dir="${build_dir}/${model}"
model_config="${model_dir}/.config"
kernel_image_dir="${build_dir}/${model}_kernel_images"
kernel_basename="linux-${model}_kernel_image"
distrib_dir="${model_dir}/tmp/distrib"
kernel_distrib_dir="${distrib_dir}/boot"
lib_dir="${distrib_dir}/lib"

# create the build directory structure if it does not exist (-p makes parents)
[[ ! -d "${build_root}" ]]         && mkdir -pv "${build_root}"
[[ ! -d "${sources_dir}" ]]        && mkdir -pv "${sources_dir}"
[[ ! -d "${config_dir}" ]]         && mkdir -pv "${config_dir}"
[[ ! -d "${build_dir}" ]]          && mkdir -pv "${build_dir}"
[[ ! -d "${model_dir}" ]]          && mkdir -pv "${model_dir}"
[[ ! -d "${kernel_image_dir}" ]]   && mkdir -pv "${kernel_image_dir}"

# create the staging directory structure if it does not exist
[[ ! -d "${distrib_dir}" ]]        && mkdir -pv "${distrib_dir}"
[[ ! -d "${kernel_distrib_dir}" ]] && mkdir -pv "${kernel_distrib_dir}"
[[ ! -d "${lib_dir}" ]]            && mkdir -pv "${lib_dir}"

# set up the cross-building make command
make_model='MAKEOPTS="-j16 -l4" FEATURES=" -userpriv -distcc -distcc-pump" '
make_model+="make O=${model_dir}/ ARCH=${arch} CROSS_COMPILE=${cross_compile} "

# get and set version number and name
old_dir=$PWD
message "Old pwd: ${old_dir}" && cd ${sources_dir} && message "Now working in $PWD"
version_number=$(eval ${make_model} -s kernelversion)
d_message "version_number: ${version_number}" 2
myversion="${version_number}-gentoo"
kernel_image_name="${kernel_basename}-${version_number}"

devel_dir="${my_devel_dir}"
ebuild_dir="${my_ebuild_dir}/${kernel_basename}"
publish_cmd_file="${build_dir}/publish_${kernel_image_name}"
[[ ! -d "${ebuild_dir}" ]]         && mkdir -pv "${ebuild_dir}"

command_sequence=(
'cp -v ${model_config} ${config_dir}/.config.bak'
'eval ${make_model} mrproper'
'cp -v ${config_dir}/.config.bak ${model_config}'
'eval ${make_model} prepare'
'eval ${make_model} oldconfig'
'eval ${make_model} menuconfig'
'cp -v ${model_config} ${config_dir}/.config.${version_number}'
'eval ${make_model} zImage'
'eval ${make_model} modules'
'eval ${make_model} dtbs'
'clean_distrib_dirs'
'install_kernel'
'install_modules'
'install_dtbs'
'make_tarball'
'publish_source_and_ebuild_update'
)

#-----[ functions ]--------------------------------------------------

new_prompt()        # set external variable $answer based on reponse to prompt $1
{ ps=$1; echo; echo; CUU; SCP; message_n "$ps [Yes/no/skip|Yns]: " && read answer; # '=~' not in busybox
while ! expr "${answer:0:1}" : [yYnNsS] >/dev/null;  # answer not a regex match
do RCP; echo -en "$(repeat ' ' $(termwidth))";  ## blank the line
RCP; message_n "$ps [Yes/no/skip|Yns]: " && read answer; done; }

display_config()
{
message "${BMon}Current Configuration:${Boff}"
d_message "${LBon}..........CONF_DIR=[${BWon}$CONF_DIR${LBon}]${Boff}" 1
d_message "${LBon}.........myversion=[${BWon}$myversion${LBon}]${Boff}" 1
d_message "${LBon}....version_number=[${BWon}$version_number${LBon}]${Boff}" 1
d_message "${LBon}........build_root=[${BWon}$build_root${LBon}]${Boff}" 1
d_message "${LBon}.......sources_dir=[${BWon}$sources_dir${LBon}]${Boff}" 1
d_message "${LBon}........config_dir=[${BWon}$config_dir${LBon}]${Boff}" 1
d_message "${LBon}.........build_dir=[${BWon}$build_dir${LBon}]${Boff}" 1
d_message "${LBon}........model_dir=[${BWon}$model_dir${LBon}]${Boff}" 1
d_message "${LBon}.....model_config=[${BWon}$model_config${LBon}]${Boff}" 1
d_message "${LBon}.......distrib_dir=[${BWon}$distrib_dir${LBon}]${Boff}" 1
d_message "${LBon}..kernel_image_dir=[${BWon}$kernel_image_dir${LBon}]${Boff}" 1
d_message "${LBon}kernel_distrib_dir=[${BWon}$kernel_distrib_dir${LBon}]${Boff}" 1
d_message "${LBon}...........lib_dir=[${BWon}$lib_dir${LBon}]${Boff}" 1
d_message "${LBon}...kernel_basename=[${BWon}$kernel_basename${LBon}]${Boff}" 1
d_message "${LBon}.kernel_image_name=[${BWon}$kernel_image_name${LBon}]${Boff}" 1
d_message "${LBon}.........devel_dir=[${BWon}$devel_dir${LBon}]${Boff}" 1
d_message "${LBon}........ebuild_dir=[${BWon}$ebuild_dir${LBon}]${Boff}" 1
d_message "${LBon}..     status_file=[${BWon}$status_file${LBon}]${Boff}" 1
d_message "${LBon}..publish_cmd_file=[${BWon}$publish_cmd_file${LBon}]${Boff}" 1
d_message "${LBon}.......make_model=[${BWon}$make_model${LBon}]${Boff}" 1
}

clean_distrib_dirs()
{
  ## remove regular files from *_distrib_dir and everything from lib_dir
  message "${LBon}Cleaning the distribution staging directory...${Boff}"
  for x in $distrib_dir $kernel_distrib_dir
  do
    [[ -d $x ]] && find $x -maxdepth 1 -type f -iname '*' -delete
  done
  [[ -d $lib_dir ]] && find $lib_dir -mindepth 1 -iname '*' -delete
  # clean the make and staging dirs
}

install_kernel()
{
  # stage kernel
  cd ${sources_dir} && message "Now working in $PWD"
  message "${LBon}Staging the kernel...${Boff}"
  cp -av ${model_dir}/arch/arm/boot/zImage ${kernel_distrib_dir}/
}

install_modules()
{
  # stage modules
  cd ${sources_dir} && message "Now working in $PWD"
  message "${LBon}Staging the modules...${Boff}"
  eval "${make_model} INSTALL_MOD_PATH=${distrib_dir} modules_install"

  # fix the build and source symlinks
  message "${LBon}Fixing the ${lib_dir}/modules/${version_number}/build symlink...${Boff}"
  cd ${lib_dir}/modules/${version_number} && message "Now working in $PWD"
  rm -v build 2>/dev/null
  ln -snfv /usr/src/linux build
  eval $link_command
  message "${LBon}Fixing the ${lib_dir}/modules/${version_number}/source symlink...${Boff}"
  rm -v source 2>/dev/null
  ln -snfv /usr/src/linux source
  cd $old_dir && message "Now working in $PWD"
}

install_dtbs()
{
  # stage modules
  cd ${sources_dir} && message "Now working in $PWD"
  message "${LBon}Staging the device tree files (dtbs)...${Boff}"
  eval "${make_model} INSTALL_DTBS_PATH=${kernel_distrib_dir}/dts/ dtbs_install"
  # copy the one dtb file we need up to boot
  message "${LBon}Staging the tinker-s dtb file...${Boff}"
  cp -av ${kernel_distrib_dir}/dts/rk3288-tinker-s.dtb ${kernel_distrib_dir}/
}

make_tarball()
{
  message "${BGon}Entering $distrib_dir${Boff}"
  cd $distrib_dir
  d_message "pwd: $(pwd)" 2

  # create staged tar archive
  message "${LBon}Creating the tar archive...${Boff}"

  # create tarball from staged contents; don't include kernel sources, firmware, or extra device tree files
  tar_command="tar "
  tar_command+="  --exclude lib/modules/${version_number}/source/"
  tar_command+="  --exclude lib/firmware"
  tar_command+="  --exclude boot/dts"
  tar_command+="  -cvjf ${kernel_image_name}.tar.bz2 boot lib"
  eval $tar_command && \
  message "${BYon}Complete.  Your tarball is located in the ${LBon}${distrib_dir}${BYon} directory${Boff}" || \
  E_message "${BRon}Something went wrong -- refer to output above${Boff}"
  cd $old_dir && message "Now working in $PWD"
}

publish_source_and_ebuild_update()
{
echo; message "copying package ${distrib_dir}/${kernel_image_name}.tar.bz2 to ${devel_dir}/"
cp -v ${distrib_dir}/${kernel_image_name}.tar.bz2 ${devel_dir}/
message "changing ownership for upload"
chown joe:joe ${devel_dir}/${kernel_image_name}.tar.bz2

echo; message "copying kernel [ ${kernel_image_name}-${version_number} ] files to server at [ ${kernel_image_dir} ]"
cp -v ${distrib_dir}/boot/* ${kernel_image_dir}/

echo; message "Updating symlink to kernel for ${model}"

cd ${kernel_image_dir} && message "Now working in $PWD"
ln -snf zImage-${version_number}-gentoo zImage
cd ${old_dir} && message "Now working in $PWD"

message "Listing contents of ${kernel_image_dir}"
ls -al ${kernel_image_dir}/

echo; message "Building publish_cmd_file [ ${publish_cmd_file} ]..."
echo "cd ${devel_dir}/" > ${publish_cmd_file}
echo "echo new PWD: \${PWD}" >> ${publish_cmd_file}
echo "git pull" >> ${publish_cmd_file}
echo "git status" >> ${publish_cmd_file}
echo "git add ${kernel_image_name}.tar.bz2" >> ${publish_cmd_file}
echo "git commit -m \"adding ${kernel_image_name}\"" >> ${publish_cmd_file}
echo "git push origin master" >> ${publish_cmd_file}
echo  >> ${publish_cmd_file}
echo "cd ${ebuild_dir}/" >> ${publish_cmd_file}
echo "echo new PWD: \${PWD}" >> ${publish_cmd_file}
ebuild_list=()

for x in $(find ${ebuild_dir} -type f -iname "linux-*" | sort)
do
ebuild_list+=("${x}")
done
old_version=$(echo ${ebuild_list[$((${#ebuild_list[@]}-1))]} | sed "s|${ebuild_dir}/${kernel_basename}-||" | sed 's|.ebuild||')
echo "old version: ${old_version}"
echo "new version: ${version_number}"

echo "cp ${ebuild_dir}/${kernel_basename}-${old_version}.ebuild ${ebuild_dir}/${kernel_image_name}.ebuild" >> ${publish_cmd_file}
echo "sed -i \"s|${old_version}|${version_number}|\" ${ebuild_dir}/${kernel_image_name}.ebuild" >> ${publish_cmd_file}
echo "rm ${ebuild_dir}/Manifest" >> ${publish_cmd_file}
echo "pkgdev manifest -f -d ${DISTDIR}" >> ${publish_cmd_file}
echo "git pull" >> ${publish_cmd_file}
echo "git status" >> ${publish_cmd_file}
echo "git add Manifest" >> ${publish_cmd_file}
echo "git add ../../metadata/md5-cache/sys-kernel/${kernel_image_name}" >> ${publish_cmd_file}
echo "git add ${kernel_image_name}.ebuild" >> ${publish_cmd_file}
echo "git commit -m \"adding ${kernel_image_name}\"" >> ${publish_cmd_file}
echo "git push origin master" >> ${publish_cmd_file}

cd ${old_dir}

separator "contents of ${publish_cmd_file} " $(hostname)
cat ${publish_cmd_file}
separator "running ${publish_cmd_file}" $(hostname)
chown joe:joe ${publish_cmd_file}
chmod +x ${publish_cmd_file}
sudo -u joe ${publish_cmd_file}
}

usage() {
  message "Usage: kernelupdate-tinker [-s|-r]"
  message "  -s | --status --> return status (next step, step_number)"
  message "  -r | --resume --> resume proccessing (with next step, step_number)"
  exit
}

#-----[ main script ]------------------------------------------------
checkroot
separator "kernelupdate-tinker-${BUILD}"
starting_step=0

[[ $# -gt 1 ]] && E_message "Invalid Arguments" && usage

[[ $# -eq 1 ]] && case $1 in
  "-s" | "--status" )
      read starting_step < ${status_file};
      message "${BWon}Status: Step $(($starting_step - 1)) complete; next step would be [ ${BMon}$starting_step${BWon} ] ( ${BGon}${command_sequence[starting_step]}${BWon} )${Boff}";
      exit;
      ;;
  "-r" | "--resume" )
      read starting_step < ${status_file};
      message "${BWon}Resuming at step [ ${BMon}$starting_step${BWon} ] ( ${BGon}${command_sequence[starting_step]}${BWon} )${Boff}";
      ;;
  *             )
      # default - error
      E_message "Error: bad argument [ $1 ]";
      usage;
      ;;
esac


display_config
sh_countdown 4

answer=""
if [[ $starting_step -eq 0 ]]
then

  do_first_prompt="\n${BYon}Remember, you must first have valid sources in '${sources_dir}'. Here are several ways -- \n${Boff}"
  do_first_prompt+="\n"
  do_first_prompt+="${LBon}# Clone from kernel.org, Github's torvalds/linux only mirrors the\n${Boff}"
  do_first_prompt+="${LBon}# master branch, not the LTS ones (see https://github.com/torvalds/linux/branches).\n${Boff}"
  do_first_prompt+="${BWon}  cd /usr/armv7a-unknown-linux-gnueabihf/usr/src\n${Boff}"
  do_first_prompt+="${BWon}  git clone https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git\n${Boff}"
  do_first_prompt+="${BWon}  cd linux\n${Boff}"
  do_first_prompt+="${BWon}  git branch --list --remotes\n${Boff}"
  do_first_prompt+="${BWon}  git branch --show-current\n${Boff}"
  do_first_prompt+="${BWon}  git checkout linux-<new_LTS_version>.y\n${Boff}"
  do_first_prompt+="${LBon}# Fetch Tinkerboard kernel config\n${Boff}"
  do_first_prompt+="${BWon}  curl -L https://raw.githubusercontent.com/TinkerBoard/debian_kernel/develop/arch/arm/configs/miniarm-rk3288_defconfig '\' \n${Boff}"
  do_first_prompt+="${BWon}    -o arch/arm/configs/miniarm-rk3288_defconfig\n${Boff}"
  do_first_prompt+="${BWon}  cd /home/joe/\n${Boff}"
  do_first_prompt+="${BWon}  mkdir MyTinkerboardFiles\n${Boff}"
  do_first_prompt+="${BWon}  cd MyTinkerboardFiles/\n${Boff}"
  do_first_prompt+="${BWon}  ln -snf /usr/armv7a-unknown-linux-gnueabihf/usr/src/linux linux\n${Boff}"
  do_first_prompt+="\n"
  do_first_prompt+="${LBon}# Just wget the current version (e.g. below, 6.4.12) from kernel.org --\n${Boff}"
  do_first_prompt+="${BWon}  cd /usr/armv7a-unknown-linux-gnueabihf/usr/src\n${Boff}"
  do_first_prompt+="${BWon}  wget https://cdn.kernel.org/pub/linux/kernel/v6.x/linux-6.4.12.tar.xz\n${Boff}"
  do_first_prompt+="${BWon}  tar xvpf linux-6.4.12.tar.xz\n${Boff}"
  do_first_prompt+="${BWon}  cd /home/joe/\n${Boff}"
  do_first_prompt+="${BWon}  mkdir MyTinkerboardFiles\n${Boff}"
  do_first_prompt+="${BWon}  cd MyTinkerboardFiles/\n${Boff}"
  do_first_prompt+="${BWon}  ln -snf /usr/armv7a-unknown-linux-gnueabihf/usr/src/linux-6.5.1 linux\n${Boff}"
  do_first_prompt+="\n"
  do_first_prompt+="${LBon}# Manually clone raspberry-pi sources\n${Boff}"
  do_first_prompt+="${BWon}  cd /usr/armv7a-unknown-linux-gnueabihf/usr/src\n${Boff}"
  do_first_prompt+="${BWon}  git clone --depth 1 git://github.com/raspberrypi/linux.git\n${Boff}"
  do_first_prompt+="${BWon}  ln -snf /usr/armv7a-unknown-linux-gnueabihf/usr/src/linux linux\n${Boff}"
  do_first_prompt+="\n"
  do_first_prompt+="${LBon}# Alternatively, you might be able to \n${Boff}"
  do_first_prompt+="${BWon}  emerge sys-kernel/gentoo-sources ${LBon}or\n${Boff}"
  do_first_prompt+="${BWon}  emerge sys-kernel/raspberrypi-sources \n${Boff}"
  do_first_prompt+="${BWon}  ln -snf /usr/src/linux-<identifier> linux\n${Boff}"
  do_first_prompt+="${LBon}  ... to link to /usr/source/linux\n${Boff}"
  do_first_prompt+="${LBon}  ( IF gentoo-sources can make dtbs [which as of 6.5.1 it cannot] )\n\n${Boff}"
  prompt "${do_first_prompt}${BYon}Did you already do this? ${Boff}?"
  [[ ! $answer == [Yy] ]] && exit
else
  do_first_prompt="${BMon}Resuming at step [ ${BWon}$starting_step${BMon} ] ( ${BGon}${command_sequence[starting_step]}${BMon} )${Boff}\n"
  do_first_prompt+="${BYon}Please verify configuration above.${Boff}"
  prompt "${do_first_prompt}\n${LBon} Continue? ${Boff}?"
  [[ ! $answer == [Yy] ]] && exit
fi

#  source joetoo's custom setnodistpath tool, to drop distcc and ccache from PATH
message "${BMon}About to source ${BGon}setnodistpath${BMon} ..."
source /usr/local/sbin/setnodistpath && echo "PATH:  $PATH"
echo
for ((step_number=${starting_step}; step_number<${#command_sequence[@]}; step_number++))
do
  d_message "Writing step_number [ $step_number ] to status_file ( $status_file )" 2
  echo $step_number > ${status_file}
  answer=""
  new_prompt "${BMon}Are you ready to run ${BGon}\"${command_sequence[step_number]}\"${BMon}?${Boff}"
  case $answer in
    [Yy] )  # execute this command and continue
      message "${LBon}About to run \"${BYon}${command_sequence[step_number]}${LBon}\"...${Boff}" ; \
      eval ${command_sequence[step_number]}; right_status $? ;;
    [Ss] ) ;; # skip this command and continue
    *    )  # abort due to negative answer
      message "${BRon}As instructed, not running ${BGon}\"${command_sequence[step_number]}\"${BRon}. Quitting...${Boff}" ; \
      exit ;;
  esac
done
final_msg="${BMon}zImage, modules, and dtb file for rk2388-tinker-s successfully staged in\n"
final_msg+="${build_dir}/${model} and published in ${kernel_image_name}.ebuild${Boff}"
message "${final_msg}"
